# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 18) do

  create_table "access_codes", :force => true do |t|
  end

  create_table "events", :force => true do |t|
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

  create_table "vap_accesses", :force => true do |t|
    t.column "event_id", :integer,                                 :null => false
    t.column "name",     :string,  :limit => 32, :default => "",   :null => false
    t.column "active",   :boolean,               :default => true, :null => false
  end

  create_table "vap_days", :force => true do |t|
    t.column "date",       :date
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  create_table "vap_dirmaps", :force => true do |t|
    t.column "event_id",      :integer,                                         :null => false
    t.column "vap_access_id", :integer,                                         :null => false
    t.column "directions",    :text,                                            :null => false
    t.column "map",           :binary,                                          :null => false
    t.column "active",        :boolean,               :default => true,         :null => false
    t.column "mime_type",     :string,  :limit => 32, :default => "image/jpeg", :null => false
  end

  create_table "vap_purposes", :force => true do |t|
    t.column "name",     :string,  :limit => 32, :default => "",   :null => false
    t.column "active",   :boolean,               :default => true, :null => false
    t.column "event_id", :integer,               :default => 0,    :null => false
  end

  create_table "vap_request_days", :force => true do |t|
    t.column "vap_day_id",     :integer
    t.column "vap_request_id", :integer
  end

  create_table "vap_requests", :force => true do |t|
    t.column "event_id",                :integer,                :default => 0
    t.column "department",              :string,   :limit => 64, :default => "", :null => false
    t.column "email",                   :string,   :limit => 64, :default => "", :null => false
    t.column "access_date",             :date
    t.column "delivery_time",           :time
    t.column "vendor",                  :string,   :limit => 64, :default => "", :null => false
    t.column "driver_name",             :string,   :limit => 64, :default => "", :null => false
    t.column "contact_name",            :string,   :limit => 64, :default => "", :null => false
    t.column "contact_phone",           :string,   :limit => 32, :default => "", :null => false
    t.column "vap_purpose_id",          :integer
    t.column "vap_purpose_other",       :string,   :limit => 32
    t.column "vap_access_id",           :integer
    t.column "vap_vehicle_type_id",     :integer
    t.column "vap_vehicle_type_other",  :string,   :limit => 32
    t.column "vehicle_color",           :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",              :datetime
    t.column "updated_at",              :datetime
    t.column "delivery_ampm",           :string,   :limit => 0,  :default => "", :null => false
    t.column "vap_access_other",        :string,   :limit => 32
    t.column "driver_license",          :string,   :limit => 32
    t.column "driver_birth_date",       :date
    t.column "driver_license_state",    :string,   :limit => 2
    t.column "delivery_location",       :string
    t.column "permalink",               :string
    t.column "passenger_name",          :string
    t.column "passenger_license",       :string,   :limit => 32
    t.column "passenger_date_of_birth", :date
    t.column "passenger_license_state", :string,   :limit => 2
  end

  add_index "vap_requests", ["permalink"], :name => "index_vap_requests_on_permalink"

  create_table "vap_vehicle_types", :force => true do |t|
    t.column "name",   :string,  :limit => 32, :default => "",   :null => false
    t.column "active", :boolean,               :default => true, :null => false
  end

end
